command:
  - ${env}
  - python
  - -m
  - train.sft
method: bayes
metric:
  goal: minimize
  name: eval/loss
parameters:
  learning_rate:
    distribution: 'log_uniform_values'
    min: 1e-5
    max: 2e-4
  warmup_ratio:
    distribution: 'uniform'
    min: 0.01
    max: 0.1
  lora_rank:
    values: [8, 16, 32]
  lora_alpha:
    values: [16, 32, 64, 128]