_wandb:
    value:
        cli_version: 0.24.0
        e:
            web45pd6v7gbn1rbh5n6tw01k56n21kn:
                email: shultra2@gmail.com
                executable: /Users/masang/miniconda/envs/langchain/bin/python
                git:
                    commit: 66450a3f8337cf3581d9064c74da7cc7e276d5bc
                    remote: https://github.com/Sanghoney96/codingtest-solution-generator.git
                host: sangheon-ui-MacBook-Air.local
                os: macOS-26.2-arm64-arm-64bit
                program: -m train.sft
                python: CPython 3.11.11
                root: /Users/masang/Desktop/side-projects/llm-fine-tuning
                startedAt: "2026-01-18T10:10:11.474599Z"
                writerId: web45pd6v7gbn1rbh5n6tw01k56n21kn
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
                - 105
            "3":
                - 13
            "4": 3.11.11
            "5": 0.24.0
            "6": 4.57.3
            "12": 0.24.0
            "13": darwin-arm64
